language: python
sudo: false
python:
  - "3.5"
branches:
  only:
    - master
addons:
 apt:
   packages:
   - pandoc
   - xsltproc
install:
  - pip install xml2rfc mako
script:
  - make
after_success:
  - openssl aes-256-cbc -K $encrypted_303da1fa4406_key -iv $encrypted_303da1fa4406_iv -in .travis.d/deploy-rsa.enc -out ~/.ssh/deploy-rsa -d
  - chmod 600 ~/.ssh/deploy-rsa
  - cp .travis.d/ssh-config ~/.ssh/config
  - ls -l ~/.ssh
  - VERSION=$(git describe --always)
  - mkdir gh-pages
  - cd gh-pages
  - mv ../*.txt ../*.html .
  - ../.travis.d/make-index.py . > index.html
  - git config --global user.name 'Travis CI'; git config --global user.email 'no-reply@travis-ci.org'
  - git init
  - git remote add deploy target:icnrg/draft-icnrg-harmonization
  - git add .
  - git commit -m "Compiled doc based on $VERSION"
  - git push deploy HEAD:refs/heads/gh-pages -f
